# TME 1 - Bonus :  Evaluation des résultats de  méthode de Prédiction de gènes

**Nom etudiant 1 :TRAORE Gnegnery Kassoum**

**Nom etudiant 2 : ZAMORE Kenjy 21107422**

### A) Matrice de confusion et mesures de performance 

Il est nécessaire d’avoir une méthode pour évaluer la qualité des prédictions obtenues pour les coordonnées des gènes. Est ce que certains gènes sont ratés par la prédiction, ou est-ce qu’au contraire certains des gènes sont systématiquement surannotés alors qu’il s’agit d’une région intergénique (entre les gènes) ? Toute l’information peut être résumée en construisant le tableau de valeurs suivante, appelée matrice de confusion. Pour cela nous attribuons à chaque nucléotide d’un génome donné la valeur 0 ou 1, 0 si le nucléotide ne fait pas partie d’un gène et 1 si il en fait partie. La matrice de confusion est calculée comme ce tableau. 

![](matriceconfusion.png "")

On résume ensuite la qualité de l’annotation avec les métriques suivantes : 

   + La sensibilité  (= ``11/(11+10)``) <br>
Sen = (le taux de vrais positifs) / (le taux de vrais positifs + le taux de faux négatifs)

   + La spécificité (= ``00 / (00+01)``) <br>
Spe = (le taux de vrais négatifs) / (le taux de vrais négatifs + le taux de faux positifs)

   + La valeur prédictive VP (= ``11 / (11+01)``) est le taux de vrais positifs parmi ceux prédits comme positifs <br>
VP = (le taux de vrais positifs) / (le taux de vrais positifs + le taux de faux positifs)


**Nous allons d'abord coder plusieurs fonctions qui seront utilisés plustard.**

<b>Question 1)</b> Ecrivez une fonction ``eval_res`` qui calcule la **Sen**, la **Spe** et **VP** (la valeur prédictive) à partir d’une matrice de confusion et renvoie un tuple à trois dimensions. La matrice de confusion sera codée comme un tableau à deux dimension, _e.g._ une liste de listes ou une matrice de numpy.

In [6]:
import doctest # Pour pouvoir utiliser doctest.testmod()
import numpy as np

In [7]:
# Question 1
def eval_res(matconf):
    """Renvoi un tuple avec la sensibilité, la spécificité et la valeur prédictive.
    entrée1 matconf : matrice de confusion (les positions contient VP, FP, FN, VN) 
    sortie1 sen: sensibilité 
    sortie2 spe: spécificité 
    sortie3 vp: sensibi valeur prédictive 
    >>> eval_res(eval_res([[4, 1], [1, 3]]))
    (0.75, 0.8, 0.75)
    """
    print(matconf)
    sen = matconf[1][1] / (matconf[1][1] + matconf[1][0]) 
    spe = matconf[0][0] / (matconf[0][0] + matconf[0][1])
    vp = matconf[1][1] / (matconf[1][1] + matconf[0][1])
    return (sen, spe, vp)
#doctest.testmod()

In [8]:
assert eval_res([[50, 10], [5, 100]]) == (100 / 105, 50 / 60, 100 / 110)

[[50, 10], [5, 100]]

<b>Question 2)</b> Ecrivez une fonction ``ecrit_intervalle`` qui, à partir des deux listes des positions de début et de fin des gènes sur le brin sens et de la longueur du génome, recode une grande liste avec la valeur 1 pour les positions qui sont des gènes et 0 sinon. Attention, il faut tenir compte des cas possibles où des gènes se chevauchent. Vous pourrez par exemple initialiser une liste avec ``lg`` valeurs à ``0`` et traiter ensuite les intervalles séquentiellement.

In [9]:
# Question 2
def ecrit_intervalle(positions_debut, positions_fin, len_genome):
    """
    Renvoie une liste binaire avec un élément par base du génome.
    1 indique la présence d'un gène.
    entrée1 positions_debut : liste contenant les positions de debut des genes
    entrée2 positions_fin : liste contenant les positions de fin des genes
    entrée3 len_genome : taille du genome
    sortie1 genome_list : Liste binaire avec un élément par base du génome
    

    >>> ecrit_intervalle([2, 10, 15], [7, 12, 20], 22)
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0]
    """
    genome_list = [0 for _ in range(len_genome)] #initialise tous les positions à zero
    for i in range(len(positions_debut)):
        debut = positions_debut[i]
        fin = positions_fin[i]
        for j in range(debut, fin+1):
            genome_list[j] = 1
   
    return genome_list

assert ecrit_intervalle([2, 10, 15], [7, 12, 20], 22) == [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0]
#doctest.testmod()

**Question 3)** Ecrivez la fonction ``compare_intervalle`` qui compare deux listes produites par la fonction ``ecrit_intervalle``, et renvoie la matrice de confusion.  
    Par exemple, si les deux listes données en paramètre sont  
    ``génome =[0,0,1,1,1,1,1,1,0,0,1,1,1,0,0,1,1,1,1,1,1,0]`` et  
    ``ORFs   =[0,0,0,1,1,1,1,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0]``, on a :  

| Genome / ORF | 0 | 1 |
|---|---|---| 
| **0** | 7 | 0  |
| **1** | 4 | 11 |

In [10]:
# Question 3
def compare_intervalles(intervalle_1, intervalle_2):
    """Renvoi la matrice de confusion.
    entrée1 intervalle_1: Liste binaire representant un genome de reference
    entrée2 intervalle_2: Liste binaire representant un les predictions de genes
    sortie1 matrix: matrice de confusion
    >>> compare_intervalles([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0])
    [[7, 0], [4, 11]]
    """

    VP, FP, FN, VN = 0, 0, 0, 0
    for i in range(len(intervalle_1)):
        if intervalle_1[i] == intervalle_2[i]:
            if intervalle_1[i] == 1:
                VP += 1
            else:
                VN += 1

        else:
            if intervalle_2[i] == 0:
                FN += 1
            else:
                FP += 1
        
    matrix = [[VN, FP], [FN, VP]]

    return matrix

assert compare_intervalles([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0]) == [[7, 0], [4, 11]]

### B) Evaluation sur _E. coli_
Nous allons comparer l’annotation des gènes de E. coli disponible au NCBI avec la prédiction par les ORFs realisé au TME precedent.
**Attention, certains gènes définit dans les fichiers .tab sont non-codant (rRNA transfer, rRNA ribossomal). Ces gènes ne commencent pas par un codon START et nous allons les ignorer dans notre comparaison**. Nous allons donc travailler seulement avec les lignes "protein_coding" et le strand "+".

Nous allons utiliser pandas, une structuré de données puissante qui va simplifier nos analyses.

Pour apprendre les bases on vous conseil les tutoriaux et vidéos suivant

*   https://eric.univ-lyon2.fr/~ricco/tanagra/fichiers/fr_Tanagra_Data_Manipulation_Pandas.pdf
*   https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html (doc en anglais)
*   https://www.youtube.com/watch?v=zZkNOdBWgFQ&t=187s (video en français)

In [11]:
import pandas as pd
import gzip
import shutil
import urllib.request

<b>Preparation :</b> Telecharger le fichier feature_table de E. coli qui contient l'annotation de son genome

In [12]:
#Telecharger le fichier feature_table de E. coli qui contient l'annotation de son genome
#Ne fonctionne pas
#urllib.request.urlretrieve(
    #'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/026/345/GCF_000026345.1_ASM2634v1/GCF_000026345.1_ASM2634v1_feature_table.txt.gz',
    #'GCF_000026345.1_ASM2634v1_feature_table.txt.gz')

In [13]:
#Decompresser le fichier
with gzip.open('GCF_000026345.1_ASM2634v1_feature_table.txt.gz', 'rb') as f_in:
    with open('GCF_000026345.1_ASM2634v1_feature_table.txt', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)

**Question 1)**: Lire le fichier `GCF_000026345.1_ASM2634v1_feature_table.txt` à l'aide de Pandas

In [14]:
#Lire le fichier à l'aide de Pandas
feature_table = pd.read_csv('GCF_000026345.1_ASM2634v1_feature_table.txt', sep='\t')

In [15]:
#afficher les premières 5 lignes
feature_table.head(5)

,# feature,class,assembly,assembly_unit,seq_type,chromosome,genomic_accession,start,end,strand,product_accession,non-redundant_refseq,related_accession,name,symbol,GeneID,locus_tag,feature_interval_length,product_length,attributes
0,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,189,254,+,NaN,NaN,NaN,NaN,thrL,NaN,ECIAI39_RS00005,66,NaN,old_locus_tag=ECIAI39_4936
1,CDS,with_protein,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,189,254,+,WP_001386572.1,WP_001386572.1,NaN,thr operon leader peptide,thrL,NaN,ECIAI39_RS00005,66,21.0,NaN
2,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,335,2797,+,NaN,NaN,NaN,NaN,thrA,NaN,ECIAI39_RS00010,2463,NaN,old_locus_tag=ECIAI39_0001
3,CDS,with_protein,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,335,2797,+,WP_001264707.1,WP_001264707.1,NaN,bifunctional aspartate kinase/homoserine dehyd...,thrA,NaN,ECIAI39_RS00010,2463,820.0,NaN
4,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,2799,3731,+,NaN,NaN,NaN,NaN,thrB,NaN,ECIAI39_RS00015,933,NaN,old_locus_tag=ECIAI39_0002

**Question 2)**: Filtrer feature table et laisser seulement les lignes contenant "protein_coding" et le strand "+".

In [20]:
df = feature_table[feature_table["strand"] == "+"]
df = df[df["class"] == "protein_coding"]
df.head(10)
#df[df["start"] == 292]

,# feature,class,assembly,assembly_unit,seq_type,chromosome,genomic_accession,start,end,strand,product_accession,non-redundant_refseq,related_accession,name,symbol,GeneID,locus_tag,feature_interval_length,product_length,attributes
0,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,189,254,+,NaN,NaN,NaN,NaN,thrL,NaN,ECIAI39_RS00005,66,NaN,old_locus_tag=ECIAI39_4936
2,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,335,2797,+,NaN,NaN,NaN,NaN,thrA,NaN,ECIAI39_RS00010,2463,NaN,old_locus_tag=ECIAI39_0001
4,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,2799,3731,+,NaN,NaN,NaN,NaN,thrB,NaN,ECIAI39_RS00015,933,NaN,old_locus_tag=ECIAI39_0002
6,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,3732,5018,+,NaN,NaN,NaN,NaN,thrC,NaN,ECIAI39_RS00020,1287,NaN,old_locus_tag=ECIAI39_0003
8,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,5232,5528,+,NaN,NaN,NaN,NaN,NaN,NaN,ECIAI39_RS00025,297,NaN,old_locus_tag=ECIAI39_0004
14,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,8123,9076,+,NaN,NaN,NaN,NaN,tal,NaN,ECIAI39_RS00040,954,NaN,old_locus_tag=ECIAI39_0008
16,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,9191,9778,+,NaN,NaN,NaN,NaN,mog,NaN,ECIAI39_RS00045,588,NaN,old_locus_tag=ECIAI39_0009
24,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,12047,13963,+,NaN,NaN,NaN,NaN,dnaK,NaN,ECIAI39_RS00065,1917,NaN,old_locus_tag=ECIAI39_0013
26,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,14052,15182,+,NaN,NaN,NaN,NaN,dnaJ,NaN,ECIAI39_RS00070,1131,NaN,old_locus_tag=ECIAI39_0014
30,gene,protein_coding,GCF_000026345.1,Primary Assembly,chromosome,NaN,NC_011750.1,16050,16811,+,NaN,NaN,NaN,NaN,NaN,NaN,ECIAI39_RS00080,762,NaN,old_locus_tag=ECIAI39_0015

**Question 3)**: Lire le fichier annotation_des_orfs.csv (produit au TME precedent) à l'aide de Pandas

In [17]:
#Lire le fichier annotation_des_orfs.csv (produit au TME precedent) à l'aide de Pandas
predicted = pd.read_csv( 'annotation_des_orfs.csv', sep='\t')
predicted = pd.read_csv( 'annotation_des_orfs.csv', sep='\t')

predicted.head(5)

   start   len                                                seq
0    292  2505  GTGCGGGCTTTTTTTTCGACCAAAGGTAACGAGGTAACAACCATGC...
1   2798   933  ATGGTTAAAGTTTATGCCCCGGCTTCCAGTGCCAATATGAGCGTCG...
2   3731  1287  ATGAAACTCTACAATCTGAAAGATCACAATGAGCAGGTCAGCTTTG...
3   8272   804  TTGATTGATGATGCTGTCGCCTGGGCGAAACAGCAGAGCAACGATC...
4  12100  1863  ATGGATGGCACCACTCCTCGTGTACTGGAGAACGCCGAAGGCGATC...

**Question 4)**: Appliquez la fonction ``compare_intervalle`` à l’annotation des gènes sur le brin sens et à la prédiction par les ORFs sur le brin sens,  puis générer la matrice de confusion.

In [ ]:
len_genome = 0 # A initialiser avec le nombre de nucleotides du genome

true_pos =[]
predicted_pos =[]
matrix = compare_intervalles(true_pos, predicted_pos)

**Question 5)**: Appliquez la fonction ``eval_res`` à la matrice de confusion et affichez Sen, Spe et VP.

In [ ]:
eval_res(matrix)